version: '2.0'
services:
  web:
    build:
      context: .
    ports:
    - "8080:8080"
    network_mode:
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - redis
  redis:
    image: redis