"""remove atribute user_id

Revision ID: 035b81cfd4b1
Revises: 9c6d9785cd76
Create Date: 2020-09-19 11:56:23.072225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035b81cfd4b1'
down_revision = '9c6d9785cd76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_user_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_user_id_fkey', 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
