"""changes

Revision ID: 9c6d9785cd76
Revises: 588049793355
Create Date: 2020-09-19 11:46:03.390967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6d9785cd76'
down_revision = '588049793355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('filename', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'user_id')
    op.drop_column('users', 'status')
    op.drop_column('users', 'filename')
    # ### end Alembic commands ###
